apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-kafka-cluster #1
spec:
  kafka:
    version: 2.6.0 #2
    replicas: 1 #3
    resources: #4
      requests:
        memory: 0.1Gi
        cpu: "1"
      limits:
        memory: 0.1Gi
        cpu: "2"
      jvmOptions: #5
        -Xms: 3276m
        -Xmx: 3276m
    listeners: #6
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config: #7
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.6"
      log.retention.hours: 1
    storage: #8
      type: persistent-claim
      size: 0.1Gi
      class: standard
      deleteClaim: false
    logging: #9
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
  zookeeper: #10
    replicas: 1
    storage:
      type: persistent-claim
      size: 2Gi
      class: standard
      deleteClaim: false
    resources:
      requests:
        memory: 0.1Gi
        cpu: "1"
      limits:
        memory: 0.1Gi
        cpu: "1.5"
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
  entityOperator: #11
    topicOperator: {}
    userOperator: {}
